apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: public-api
  description: Public API
spec:
  type: openapi
  lifecycle: production
  owner: orca
  system: association-registry
  subcomponentOf: association-registry
  definition: 
    $text: https://publiek.verenigingen.test-vlaanderen.be/docs/v1/docs.json
  links:
    - url: https://publiek.verenigingen
      title: Publieke Api
      icon: dashboard

